services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234        # Set a root password
      MYSQL_DATABASE: db_todo_app      # Your database name
    ports:
      - "3309:3306"  # Change the host port (left side) as needed
    volumes:
      - mysql_data:/var/lib/mysql


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring_boot_app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_todo_app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root    # Keep 'root' for MySQL authentication
      SPRING_DATASOURCE_PASSWORD: 1234    # Same password as for root user
    ports:
      - "8081:8080"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_app
    restart: always
    depends_on:
      - backend
    ports:
      - "4300:80"


volumes:
  mysql_data:
